version: "3"
services:
  app:
    container_name: server
    build:
      context: .
    depends_on:
      database:
        condition: service_healthy
    environment:
      STAGE: development
    ports:
      - "3000:3000"
  database:
    image: postgres:15
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    user: postgres
    environment:
      POSTGRES_PASSWORD: postgres
volumes:
  pgdata:
